tap "homebrew/bundle"
tap "homebrew/services"
# Library of 2D and 3D vector, matrix, and math operations
brew "imath"
# General-purpose data compression with high compression ratio
brew "xz"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Library for command-line editing
brew "readline"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# HTTP/2 C Library
brew "libnghttp2"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Simple terminal UI for git commands
brew "lazygit"
# Pager program similar to more
brew "less"
# Provides library functionality for FIDO U2F & FIDO 2.0, including USB
brew "libfido2"
# Apple Silicon Monitor Top written in Golang
brew "mactop"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage multiple Node.js versions
brew "nvm"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# Python package management tool
brew "poetry"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Cross-shell prompt for astronauts
brew "starship"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Generator for LS_COLORS with support for multiple color themes
brew "vivid"
# Internet file retriever
brew "wget"
# Tool for managing your YubiKey configuration
brew "ykman"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Stand alone ad blocker
cask "adguard"
# VPN for privacy and security
cask "adguard-vpn"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Cloud storage service
cask "baidunetdisk"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Voice and text chat software
cask "discord"
# European dictionary
cask "eudic"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Web browser
cask "google-chrome"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Grammarly for desktop
cask "grammarly-desktop"
# Free and open-source media player
cask "iina"
# Vector graphics editor
cask "inkscape"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Software for Logitech devices
cask "logi-options-plus"
# Full TeX Live distribution without GUI applications
cask "mactex-no-gui"
# Remote desktop client
cask "microsoft-remote-desktop"
# Minimal installer for conda
cask "miniconda"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Desktop virtualization software
cask "parallels"
# PDF reader, editor and annotator
cask "pdf-expert"
# Email client
cask "readdle-spark"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
# Break time reminder app
cask "stretchly"
# Open-source code editor
cask "visual-studio-code"
# Free messaging and calling application
cask "wechat"
# Video communication and virtual meeting platform
cask "zoom"
vscode "aaron-bond.better-comments"
vscode "adpyke.codesnap"
vscode "catppuccin.catppuccin-vsc"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.todo-tree"
vscode "hediet.vscode-drawio"
vscode "james-yu.latex-workshop"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "mikestead.dotenv"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "njpwerner.autodocstring"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "robbowen.synthwave-vscode"
vscode "streetsidesoftware.code-spell-checker"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
