# Terminal identity and truecolor
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -ga update-environment "COLORTERM"

# Prefix key
unbind C-b
set -g prefix C-a

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Mouse support
set -g mouse on

# Split panes in the current directory
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Window numbering
set -g renumber-windows on

# Status bar
set -g status-position top

# Start indexes at 1
set -g base-index 1
set -g pane-base-index 1

# Vi copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Catppuccin
run "~/.local/share/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
